### ISSUE TITLE
Swagger NumberFormatException

### ISSUE THREAD

**Issue by donghyeon-dev** [donghyeon-dev/oh-my-raid#1]
## 상황 배경
Swagger UI에서 입력값을 선택해서 테스트를 하길 원했고 `allowValues`에 값을 넣어주었다.
``` java
public class CharacterRaidInfoRequest {  
  
    @ApiModelProperty(value = "캐릭터 고유 ID", name = "characterId")  
    private Integer characterId;  
  
    @ApiModelProperty(value = "확장팩 ID(395:Legion, 396:BFA, 499:SHL, 503:DF)", name = "expansionId", allowableValues = "395,396,499,503")    private Integer expansionId;  
  
    @ApiModelProperty(value = "난이도 ID", name = "difficulty", allowableValues = "1,2,3,4")  
    private Integer difficulty;  
  
}
```
Swagger UI에서 확인했을때도 원하는 select options가 나오는것도 확인했다.
![2023-11-28 10 41 55](https://github.com/donghyeon-dev/oh-my-raid/assets/53686581/91822293-9fca-4f80-8843-cf38c42596a3)

하지만 콘솔에서 아래와 같은 오류가 발생했다.
```
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[na:na]
	at java.base/java.lang.Long.parseLong(Long.java:721) ~[na:na]
	at java.base/java.lang.Long.valueOf(Long.java:1163) ~[na:na]
	at io.swagger.models.parameters.AbstractSerializableParameter.getExample(AbstractSerializableParameter.java:412) ~[swagger-models-1.5.20.jar:1.5.20]
...
at springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(Swagger2Controller.java:105) ~[springfox-swagger2-2.9.2.jar:null]
...
```

## 원인
로그의 내용으로 보았을때 swagger에서 documentation을 swagger-model에서 Long type property의 `examlple`을 가져오는데 선언된 값이 없어서 ``""(emptyString)`` 을 변환하다가 오류가 난것 같다.
``` java
@Target({ElementType.METHOD, ElementType.FIELD})  
@Retention(RetentionPolicy.RUNTIME)  
public @interface ApiModelProperty {
...
/**  
 * A sample value for the property. */
	String example() default "";
...
}
```
Debugger를 걸어 확인해 보았고 더 자세한 이유를 찾을 수 있었다.
1. Swagger2Controller.getDocumentation()
YOU_HOST/v2/api-docs 에 사용될 JSON을 생성하기 위해 `Swagger`객체를 JSON으로 변환하는 과정에서 문제의 stack trace가 시작된다고 보여진다.
![2023-11-28 11 00 41](https://github.com/donghyeon-dev/oh-my-raid/assets/53686581/dd575d9a-387b-4178-abd6-9c0a92ca11cc)
`Swagger` 객체는 Swagger UI를 표현하기위한 정보(api URI path, Model...)를 가진 객체로 이다. `documentationCache.documentationByGroup()` 를 통해 생성된 Documentation 객체를 맵핑하여 `Swagger` 객체를 만든다. 이 객체를 `ObjectMapper`를 통해 변환하면서 발생한 오류이다.

2. ModelMapper.mapModels()
Model객체들을 반복문을 통해 Map구조에 맵핑을 한다. 이 과정에서 내가 정의한 `@ApiModelProperty` 내 속성들 값이 맵핑된다.

3. Swagger2Controller.getDocumentation()
캡쳐와 같이 일단 이 메서드는 `ResponseEntity<JSON>`을 리턴한다. 그 말은 지금 이 trace들은 어떠한 request에 대한 response인걸 알 수 있다. 그 Request는 `YOURHOST/v2/api-docs`로 SwaggerUI를 표현하기 위한 JSON을 가져오는 부분이다. 위에서 맵핑된 `Swagger` 객체를 JSON으로 변환하는 과정에서 Exception이 발생한것이다.

3. AbstractSerializableParameter.getExample()
직접적으로 Exception이 발생한 부분인데, Swagger객체의 definition(Model)을 직렬화하면서 `example` 속성을 가져오는 과정으로 보인다.
``` java
@JsonProperty("x-example")  
public Object getExample() {  
	if (example == null) {  
        return null;  
    }
	try {  
        if (BaseIntegerProperty.TYPE.equals(type)) { // type=integer
            return Long.valueOf(example);  example=""
        } else if (DecimalProperty.TYPE.equals(type)) {  
            return Double.valueOf(example);  
        } else if (BooleanProperty.TYPE.equals(type)) {  
            if ("true".equalsIgnoreCase(example) || "false".equalsIgnoreCase(defaultValue)) {  
                return Boolean.valueOf(example);  
            }        
		}    
	} catch (NumberFormatException e) {  
        LOGGER.warn(String.format("Illegal DefaultValue %s for parameter type %s", defaultValue, type), e);  
    }    return example;  
}
```

위 코드인데 `example` 속성을 Long으로 변환시 catch에 걸려서 Exception이 던져진것이다.
작성했던 CharacterRaidInfoRequest 객체는 각 컬럼에 `example` 값을 설정하지 않았고, @ApiModelProperty 어노테이션의 `example` 속성의 default값은 `""(emptyString)` 이였기에 emptyString을 Long으로 변환하는 과정에서 오류가 난것이다.

## 처리방법

`@ApiModelProperty`를 선언할때 Integer type일때는 `example` 속성에 값을 넣어주면 해결된다.
```java
@ApiModelProperty(value = "캐릭터 고유 ID", name = "characterId", example="19")  
private Integer characterId;  
  
@ApiModelProperty(value = "확장팩 ID (eg.395:Legion, 396:BFA, 499:SHL, 503:DF)", name = "expansionId"  
        , allowableValues = "395,396,499,503", example="395")  
private Integer expansionId;  
  
@ApiModelProperty(value = "난이도 ID", name = "difficulty", allowableValues = "1,2,3,4", example="4")  
private Integer difficulty;
```

**Comment by donghyeon-dev** [comment]
## 원인
로그의 내용으로 보았을때 swagger에서 documentation을 swagger-model에서 Long type property의 `examlple`을 가져오는데 선언된 값이 없어서 ``""(emptyString)`` 을 변환하다가 오류가 난것 같다.
``` java
@Target({ElementType.METHOD, ElementType.FIELD})  
@Retention(RetentionPolicy.RUNTIME)  
public @interface ApiModelProperty {
...
/**  
 * A sample value for the property. */
	String example() default "";
...
}
```
Debugger를 걸어 확인해 보았고 더 자세한 이유를 찾을 수 있었다.
1. Swagger2Controller.getDocumentation()
YOU_HOST/v2/api-docs 에 사용될 JSON을 생성하기 위해 `Swagger`객체를 JSON으로 변환하는 과정에서 문제의 stack trace가 시작된다고 보여진다.
![2023-11-28 11 00 41](https://github.com/donghyeon-dev/oh-my-raid/assets/53686581/dd575d9a-387b-4178-abd6-9c0a92ca11cc)
`Swagger` 객체는 Swagger UI를 표현하기위한 정보(api URI path, Model...)를 가진 객체로 이다. `documentationCache.documentationByGroup()` 를 통해 생성된 Documentation 객체를 맵핑하여 `Swagger` 객체를 만든다. 이 객체를 `ObjectMapper`를 통해 변환하면서 발생한 오류이다.

2. ModelMapper.mapModels()
Model객체들을 반복문을 통해 Map구조에 맵핑을 한다. 이 과정에서 내가 정의한 `@ApiModelProperty` 내 속성들 값이 맵핑된다.

3. Swagger2Controller.getDocumentation()
캡쳐와 같이 일단 이 메서드는 `ResponseEntity<JSON>`을 리턴한다. 그 말은 지금 이 trace들은 어떠한 request에 대한 response인걸 알 수 있다. 그 Request는 `YOURHOST/v2/api-docs`로 SwaggerUI를 표현하기 위한 JSON을 가져오는 부분이다. 위에서 맵핑된 `Swagger` 객체를 JSON으로 변환하는 과정에서 Exception이 발생한것이다.

3. AbstractSerializableParameter.getExample()
직접적으로 Exception이 발생한 부분인데, Swagger객체의 definition(Model)을 직렬화하면서 `example` 속성을 가져오는 과정으로 보인다.
``` java
@JsonProperty("x-example")  
public Object getExample() {  
	if (example == null) {  
        return null;  
    }
	try {  
        if (BaseIntegerProperty.TYPE.equals(type)) { // type=integer
            return Long.valueOf(example);  example=""
        } else if (DecimalProperty.TYPE.equals(type)) {  
            return Double.valueOf(example);  
        } else if (BooleanProperty.TYPE.equals(type)) {  
            if ("true".equalsIgnoreCase(example) || "false".equalsIgnoreCase(defaultValue)) {  
                return Boolean.valueOf(example);  
            }        
		}    
	} catch (NumberFormatException e) {  
        LOGGER.warn(String.format("Illegal DefaultValue %s for parameter type %s", defaultValue, type), e);  
    }    return example;  
}
```

위 코드인데 `example` 속성을 Long으로 변환시 catch에 걸려서 Exception이 던져진것이다.
작성했던 CharacterRaidInfoRequest 객체는 각 컬럼에 `example` 값을 설정하지 않았고, @ApiModelProperty 어노테이션의 `example` 속성의 default값은 `""(emptyString)` 이였기에 emptyString을 Long으로 변환하는 과정에서 오류가 난것이다.

## 처리방법

`@ApiModelProperty`를 선언할때 Integer type일때는 `example` 속성에 값을 넣어주면 해결된다.
```java
@ApiModelProperty(value = "캐릭터 고유 ID", name = "characterId", example="19")  
private Integer characterId;  
  
@ApiModelProperty(value = "확장팩 ID (eg.395:Legion, 396:BFA, 499:SHL, 503:DF)", name = "expansionId"  
        , allowableValues = "395,396,499,503", example="395")  
private Integer expansionId;  
  
@ApiModelProperty(value = "난이도 ID", name = "difficulty", allowableValues = "1,2,3,4", example="4")  
private Integer difficulty;
```
